# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7365dbda9c521e5bda666b30d7c5a24c7b54fa93c378c5b00d19893dd1bdfe64dbbb2405bcfb104c246d0581ee0958180f331828d5a355ad9fcda89d44c1dac4

test:
  secret_key_base: 206917744ddee5b9bc665f24cd18a6ed5dd37b1069aef8ecca1662f782a5c637f005566e2b16a04d73335a1c6279619aeb5587a368a92e433987229252609820

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
